name: Eighty-K
favicon: null
layout_spectrum: 0.019931806717067957
typography_spectrum: 0.23143793526105583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.926934267859906
  lightness: 0.7770905320066959
  saturation: 0.920786542352289
  rhythmicContrast: 0.5632266490720212
purpose: []
