name: Eighty-K
favicon: null
layout_spectrum: 0.6367585901170969
typography_spectrum: 0.35383394826203585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5450296956114471
  lightness: 0.4078415660187602
  saturation: 0.5559051318559796
  rhythmicContrast: 0.9454818756785244
purpose: []
