name: Eighty-K
favicon: null
layout_spectrum: 0.23007084988057613
typography_spectrum: 0.07764990208670497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7199114076793194
  lightness: 0.931006756843999
  saturation: 0.35925373155623674
  rhythmicContrast: 0.8883671066723764
purpose: []
