name: Eighty-K
favicon: null
layout_spectrum: 0.6269865641370416
typography_spectrum: 0.148366971174255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1791510300245136
  lightness: 0.43340378580614924
  saturation: 0.4838280198164284
  rhythmicContrast: 0.06755846785381436
purpose: []
