name: Eighty-K
favicon: null
layout_spectrum: 0.16604668786749244
typography_spectrum: 0.31468446482904255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23060984490439296
  lightness: 0.9526348786894232
  saturation: 0.3162237508222461
  rhythmicContrast: 0.6111361410003155
purpose: []
