name: Eighty-K
favicon: null
layout_spectrum: 0.82313381601125
typography_spectrum: 0.959868477890268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6439411691389978
  lightness: 0.9130309135653079
  saturation: 0.8835781125817448
  rhythmicContrast: 0.828577869804576
purpose: []
