name: Eighty-K
favicon: null
layout_spectrum: 0.8998300398234278
typography_spectrum: 0.5510926053393632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25315831415355206
  lightness: 0.8413844674360007
  saturation: 0.4178062474820763
  rhythmicContrast: 0.7105008810758591
purpose: []
