name: Eighty-K
favicon: null
layout_spectrum: 0.31599236163310707
typography_spectrum: 0.024540242739021778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4368595180567354
  lightness: 0.7337380044627935
  saturation: 0.6455838342662901
  rhythmicContrast: 0.6841386070009321
purpose: []
