name: Eighty-K
favicon: null
layout_spectrum: 0.4881325359456241
typography_spectrum: 0.8286550885532051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.944242759142071
  lightness: 0.1298653562553227
  saturation: 0.05426800064742565
  rhythmicContrast: 0.5338331658858806
purpose: []
