name: Eighty-K
favicon: null
layout_spectrum: 0.7755068074911833
typography_spectrum: 0.6845277466345578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5330772597808391
  lightness: 0.9021578577812761
  saturation: 0.051264723064377904
  rhythmicContrast: 0.8208646713756025
purpose: []
