name: Eighty-K
favicon: null
layout_spectrum: 0.10349949495866895
typography_spectrum: 0.019785549491643906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3845739425159991
  lightness: 0.20307891420088708
  saturation: 0.6950615725945681
  rhythmicContrast: 0.7619253299199045
purpose: []
