name: Eighty-K
favicon: null
layout_spectrum: 0.7139516768511385
typography_spectrum: 0.9165228644851595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7537585815880448
  lightness: 0.596207452006638
  saturation: 0.6945624880027026
  rhythmicContrast: 0.6703594059217721
purpose: []
