name: Eighty-K
favicon: null
layout_spectrum: 0.9331032680347562
typography_spectrum: 0.6300881041679531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7335085249505937
  lightness: 0.5170924938283861
  saturation: 0.9872395636048168
  rhythmicContrast: 0.7686141922604293
purpose: []
