name: Eighty-K
favicon: null
layout_spectrum: 0.46922118216753006
typography_spectrum: 0.07950977445580065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8031094258185476
  lightness: 0.07917315256781876
  saturation: 0.7620814605616033
  rhythmicContrast: 0.32174191484227777
purpose: []
