name: Eighty-K
favicon: null
layout_spectrum: 0.5638539772480726
typography_spectrum: 0.19147710828110576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.838926465716213
  lightness: 0.509973879205063
  saturation: 0.8058909170795232
  rhythmicContrast: 0.9451405028812587
purpose: []
