name: Eighty-K
favicon: null
layout_spectrum: 0.10287001822143793
typography_spectrum: 0.6762505013030022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.944177643628791
  lightness: 0.9720759999472648
  saturation: 0.7367752466816455
  rhythmicContrast: 0.28074845438823104
purpose: []
