name: Eighty-K
favicon: null
layout_spectrum: 0.8090802929364145
typography_spectrum: 0.10133052454330027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.615970981772989
  lightness: 0.5895328093320131
  saturation: 0.5312955460976809
  rhythmicContrast: 0.2532723071053624
purpose: []
