name: Eighty-K
favicon: null
layout_spectrum: 0.40960778505541384
typography_spectrum: 0.9404597952961922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.86470354674384
  lightness: 0.9311164258979261
  saturation: 0.35139974346384406
  rhythmicContrast: 0.294124849839136
purpose: []
