name: Eighty-K
favicon: null
layout_spectrum: 0.8740784178953618
typography_spectrum: 0.8982528147753328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7674393770284951
  lightness: 0.41729533462785184
  saturation: 0.20987685257568955
  rhythmicContrast: 0.059623751789331436
purpose: []
