name: Eighty-K
favicon: null
layout_spectrum: 0.8506796367000788
typography_spectrum: 0.5017852101009339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08076167921535671
  lightness: 0.6757503817789257
  saturation: 0.736830321373418
  rhythmicContrast: 0.034593467600643635
purpose: []
