name: Eighty-K
favicon: null
layout_spectrum: 0.13574068271555007
typography_spectrum: 0.2486681214068085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7513510352000594
  lightness: 0.3558197673410177
  saturation: 0.1029091498348862
  rhythmicContrast: 0.4872854535933584
purpose: []
