name: Eighty-K
favicon: null
layout_spectrum: 0.1643130776938051
typography_spectrum: 0.40989322680979967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8121422079857439
  lightness: 0.23501282650977373
  saturation: 0.392602905863896
  rhythmicContrast: 0.9244314297102392
purpose: []
