name: Eighty-K
favicon: null
layout_spectrum: 0.7987298618536443
typography_spectrum: 0.26257424615323544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2235675749834627
  lightness: 0.1214837187435478
  saturation: 0.7790348869748414
  rhythmicContrast: 0.1068363378290087
purpose: []
