name: Eighty-K
favicon: null
layout_spectrum: 0.7222728540655226
typography_spectrum: 0.9761150069534779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5632197256200016
  lightness: 0.9393903841264546
  saturation: 0.38986941846087575
  rhythmicContrast: 0.21135342260822654
purpose: []
