name: Eighty-K
favicon: null
layout_spectrum: 0.8116716360673308
typography_spectrum: 0.7534468888770789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.711671399185434
  lightness: 0.5545613607391715
  saturation: 0.49371040402911603
  rhythmicContrast: 0.5003796417731792
purpose: []
