name: Eighty-K
favicon: null
layout_spectrum: 0.935827643610537
typography_spectrum: 0.5284840292297304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.046236901078373194
  lightness: 0.9836288311053067
  saturation: 0.8348971225786954
  rhythmicContrast: 0.12134155328385532
purpose: []
