name: Eighty-K
favicon: null
layout_spectrum: 0.6666826624423265
typography_spectrum: 0.13997081806883216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8370844922028482
  lightness: 0.03674654313363135
  saturation: 0.6412492420058697
  rhythmicContrast: 0.3038314275909215
purpose: []
