name: Eighty-K
favicon: null
layout_spectrum: 0.1481658115517348
typography_spectrum: 0.48395765922032297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21862348215654492
  lightness: 0.8442823253571987
  saturation: 0.3847119065467268
  rhythmicContrast: 0.9423738226760179
purpose: []
