name: Eighty-K
favicon: null
layout_spectrum: 0.5269237337633967
typography_spectrum: 0.3546236183028668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.013257857179269195
  lightness: 0.11799333174712956
  saturation: 0.8697350374422967
  rhythmicContrast: 0.4348320148419589
purpose: []
