name: Eighty-K
favicon: null
layout_spectrum: 0.0027972396928817034
typography_spectrum: 0.10740307183004916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.36306538502685726
  lightness: 0.08587178401648998
  saturation: 0.043056810507550836
  rhythmicContrast: 0.5860355005133897
purpose: []
