name: Eighty-K
favicon: null
layout_spectrum: 0.3820386619772762
typography_spectrum: 0.07554547674953938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2845953281503171
  lightness: 0.3647439905907959
  saturation: 0.8059021015651524
  rhythmicContrast: 0.1834659546148032
purpose: []
