name: Eighty-K
favicon: null
layout_spectrum: 0.7306561095174402
typography_spectrum: 0.2126433930825442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6141139634419233
  lightness: 0.6040633646771312
  saturation: 0.9710727408528328
  rhythmicContrast: 0.5184011228848249
purpose: []
