name: Eighty-K
favicon: null
layout_spectrum: 0.003228849032893777
typography_spectrum: 0.8496655658818781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7494755850639194
  lightness: 0.2280681838747114
  saturation: 0.5102817735169083
  rhythmicContrast: 0.21203928487375379
purpose: []
