name: Eighty-K
favicon: null
layout_spectrum: 0.42103073140606284
typography_spectrum: 0.4537969797383994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.33876260672695935
  lightness: 0.294886548537761
  saturation: 0.3654039944522083
  rhythmicContrast: 0.07701813150197268
purpose: []
