name: Eighty-K
favicon: null
layout_spectrum: 0.5780734522268176
typography_spectrum: 0.12920398521237075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9627431884873658
  lightness: 0.14816359872929752
  saturation: 0.6480420930311084
  rhythmicContrast: 0.6903361803852022
purpose: []
