name: Eighty-K
favicon: null
layout_spectrum: 0.33696776255965233
typography_spectrum: 0.3352650513406843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1328189531341195
  lightness: 0.9762905985116959
  saturation: 0.7447541549336165
  rhythmicContrast: 0.10680634574964643
purpose: []
