name: Eighty-K
favicon: null
layout_spectrum: 0.45433122059330344
typography_spectrum: 0.033505791798233986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14503881335258484
  lightness: 0.23005915665999055
  saturation: 0.8676642957143486
  rhythmicContrast: 0.8248737840913236
purpose: []
