name: Eighty-K
favicon: null
layout_spectrum: 0.032661268254742026
typography_spectrum: 0.7403340865857899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.984780031023547
  lightness: 0.9402102814055979
  saturation: 0.5638906427193433
  rhythmicContrast: 0.19761756504885852
purpose: []
