name: Eighty-K
favicon: null
layout_spectrum: 0.37975354259833694
typography_spectrum: 0.1751901200041175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2825365741737187
  lightness: 0.7513053684961051
  saturation: 0.5288005431648344
  rhythmicContrast: 0.8500877174083143
purpose: []
