name: Eighty-K
favicon: null
layout_spectrum: 0.6441392998676747
typography_spectrum: 0.2979004164226353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6576763789635152
  lightness: 0.6699312485288829
  saturation: 0.6657937571872026
  rhythmicContrast: 0.10795478033833206
purpose: []
