name: Eighty-K
favicon: null
layout_spectrum: 0.08179890573956072
typography_spectrum: 0.49687956366688013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3639082331210375
  lightness: 0.8085972282569855
  saturation: 0.5350520799402148
  rhythmicContrast: 0.1838511312380433
purpose: []
