name: Eighty-K
favicon: null
layout_spectrum: 0.7188898106105626
typography_spectrum: 0.33897837228141725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2723331123124808
  lightness: 0.26381299225613475
  saturation: 0.6615187637507915
  rhythmicContrast: 0.9240414225496352
purpose: []
