name: Eighty-K
favicon: null
layout_spectrum: 0.4458480530884117
typography_spectrum: 0.9695498319342732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5918910640757531
  lightness: 0.8475733119994402
  saturation: 0.7147503334563226
  rhythmicContrast: 0.6244000331498682
purpose: []
