name: Eighty-K
favicon: null
layout_spectrum: 0.5273452000692487
typography_spectrum: 0.37661303277127445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7985453987494111
  lightness: 0.7936726834159344
  saturation: 0.966513309860602
  rhythmicContrast: 0.2029319212306291
purpose: []
