name: Eighty-K
favicon: null
layout_spectrum: 0.7786334403790534
typography_spectrum: 0.9721151951234788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5270894069690257
  lightness: 0.6833940476644784
  saturation: 0.5520216634031385
  rhythmicContrast: 0.20105871697887778
purpose: []
