name: Eighty-K
favicon: null
layout_spectrum: 0.5187750763725489
typography_spectrum: 0.5924593131057918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.038368945475667715
  lightness: 0.1283579315058887
  saturation: 0.47694474179297686
  rhythmicContrast: 0.23294982453808188
purpose: []
