name: Eighty-K
favicon: null
layout_spectrum: 0.13406397704966366
typography_spectrum: 0.8197081775870174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4547338141128421
  lightness: 0.45818593236617744
  saturation: 0.3706073865760118
  rhythmicContrast: 0.20149062178097665
purpose: []
