name: Eighty-K
favicon: null
layout_spectrum: 0.7293410843703896
typography_spectrum: 0.3023928813636303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6556418084073812
  lightness: 0.5876087269280106
  saturation: 0.41054264502599835
  rhythmicContrast: 0.9195909700356424
purpose: []
