name: Eighty-K
favicon: null
layout_spectrum: 0.3751509445719421
typography_spectrum: 0.9217994261998683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.13234361843205988
  lightness: 0.4963010218925774
  saturation: 0.7827083435840905
  rhythmicContrast: 0.407893750583753
purpose: []
