name: Eighty-K
favicon: null
layout_spectrum: 0.1620281129144132
typography_spectrum: 0.5970199690200388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.30722927628085017
  lightness: 0.005916120950132608
  saturation: 0.9905004231259227
  rhythmicContrast: 0.29438640107400715
purpose: []
