name: Eighty-K
favicon: null
layout_spectrum: 0.07678958890028298
typography_spectrum: 0.04895804217085242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4883368469309062
  lightness: 0.2134026433341205
  saturation: 0.4877407772000879
  rhythmicContrast: 0.38512582797557116
purpose: []
