name: Eighty-K
favicon: null
layout_spectrum: 0.3031735494732857
typography_spectrum: 0.6815278648864478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.47307120612822473
  lightness: 0.5659211883321404
  saturation: 0.15094779361970723
  rhythmicContrast: 0.28334754635579884
purpose: []
