name: Eighty-K
favicon: null
layout_spectrum: 0.4160272020380944
typography_spectrum: 0.8984200039412826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7067866546567529
  lightness: 0.09252609009854496
  saturation: 0.7060877694748342
  rhythmicContrast: 0.3207468702457845
purpose: []
