name: Eighty-K
favicon: null
layout_spectrum: 0.02724022720940411
typography_spectrum: 0.9701082182582468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7916692995931953
  lightness: 0.20959567674435675
  saturation: 0.14518088335171342
  rhythmicContrast: 0.7885890062898397
purpose: []
