name: Eighty-K
favicon: null
layout_spectrum: 0.5935679217800498
typography_spectrum: 0.4486528786364943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14441957348026335
  lightness: 0.9140411571133882
  saturation: 0.146680150879547
  rhythmicContrast: 0.3097261858638376
purpose: []
